"""empty message

Revision ID: acbe2f27029a
Revises: b7c3a6548284
Create Date: 2022-10-19 13:47:18.088384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acbe2f27029a'
down_revision = 'b7c3a6548284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('galleries', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable='False')
    op.add_column('users', sa.Column('avatar', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.alter_column('galleries', 'title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
